Server:
   port: 9001
spring:
   mvc:
    pathmatch:
          matching-strategy: ant-path-matcher
   zipkin:
     base-url: http://localhost:9411 
     
   config.import: configserver:http://localhost:8888
            
     
   datasource:
      url: jdbc:mysql://localhost:3306/olx
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Muskan@123
          
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            
      show-sql: true
            
   application:
        name: advertise-service
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true 

management:
    endpoints:
      web:
        exposure:
          include: "*"
    health:
      circuitbreakers:
        enabled: true
    endpoint:
      health:
        show-details: always



resilience4j:
  circuitbreaker:
    instances:
      VALIDATE-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
      MASTER-DATA-CIRCUIT-BREAKER:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 60
        minimumNumberOfCalls: 6
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 10s
       
             